title = "ciele৲"
base_url = "https://ciele-club.github.io/"
compile_sass = true
highlight_code = true
build_search_index = false

[extra]
email = "ciele@protonmail.com"
notion_url = "https://ciele-club.notion.site/"
